apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb-deploy
  labels:
    app: mongodb
    version: develop
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  minReadySeconds: 5
  selector:
    matchLabels:
      app: mongodb
      appFor: treinamento
  template:
    metadata:
      labels:
        app: mongodb
        appFor: treinamento
    spec:
      containers:
      - name: mongodb-container
        image: mongo:3.5
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 27017
            protocol: TCP
        resources:
          requests:
            cpu: '0.01'
            memory: '10Mi'
          limits:
            cpu: '1'
            memory: '600Mi'


  