apiVersion: apps/v1
kind: Deployment
metadata:
  name: treinamento
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: treinamento
  template:
    metadata:
      labels:
        app: treinamento  
    spec:
      containers:
        - name: treinamento
          image: drprado2/api-heros:v1
          ports:
            - containerPort: 4000
          env: 
            - name: MONGO_URL
              value: "10.36.2.6"
            - name: PORT
              value: "4000"
          resources:
            limits:
              memory: "200Mi"
              cpu: "1"
            requests:
              memory: "30Mi"
              cpu: "0.05"
      imagePullSecrets:
        - name: regcred