apiVersion: v1
kind: Service
metadata:
  name: treinamento-rs-svc
  labels:
    app: treinamento-rs
    tipo: replicaset
    svc: "true"
spec:
  selector:
      app: treinamento
      tipo: replicaset
  ports:
    - targetPort: 5000
      port: 9090
  type: LoadBalancer


