apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
  labels:
    app: mongodb
    appFor: treinamento
spec:
  containers:
    - name: mongodb-container
      ports:
        - containerPort: 27017
          protocol: TCP
      resources:
        requests:
          cpu: "0.05"
          memory: "50Mi"
        limits:
          cpu: "1"
          memory: "350Mi"
      image: mongo:3.5